# Generated by Django 4.2.28 on 2026-02-12 05:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Alumni name', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(help_text='Current job role', max_length=200)),
                ('category', models.CharField(choices=[('software-engineer', 'Software Engineer'), ('web-developer', 'Web Developer'), ('cybersecurity-analyst', 'Cybersecurity Analyst'), ('tester', 'Tester'), ('data-scientist', 'Data Scientist'), ('devops-engineer', 'DevOps Engineer'), ('mobile-developer', 'Mobile Developer'), ('other', 'Other')], default='other', max_length=50)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('experience', models.TextField(help_text='Career journey and advice')),
                ('skills', models.TextField(blank=True, help_text='Key skills (comma-separated)')),
                ('graduation_year', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_role', models.CharField(choices=[('student', 'Student'), ('alumni', 'Alumni')], default='student', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
