# Generated by Django 4.2.28 on 2026-02-09 16:08

from django.db import migrations


def seed_initial_posts(apps, schema_editor):
    Post = apps.get_model('posts', 'Post')
    
    posts_data = [
        {
            'name': 'Devesh Dabhade',
            'role': 'Software Engineer',
            'category': 'software-engineer',
            'experience': 'I started as a junior dev and focused on Python and algorithms. Internships helped a lot.'
        },
        {
            'name': 'Bhushan Badhe',
            'role': 'Web Developer',
            'category': 'web-developer',
            'experience': 'I built small projects using HTML/CSS/JS and contributed to open source. Networking helped me.'
        },
        {
            'name': 'Shaunak Hawaldar',
            'role': 'Cybersecurity Analyst',
            'category': 'cybersecurity-analyst',
            'experience': 'Certifications in ethical hacking and hands-on labs were crucial for my career.'
        },
        {
            'name': 'Saurabh Balagide',
            'role': 'Tester',
            'category': 'tester',
            'experience': 'Learning automation testing and practicing problem-solving were key steps.'
        }
    ]
    
    for post_data in posts_data:
        Post.objects.create(**post_data)


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_initial_posts),
    ]

